### ISSUE TITLE
I get messages with level "warning", although only "errors" are configured as level.

### ISSUE THREAD

**Issue by lukassarfert** [cebe/yii2-loki-log-target#1]
I have configured the logtarget as follows:

                [
                  'class' => LokiLogTarget::class,
                  ...
                  'levels' => ['error'],
                  ...
                  ],
              ],

i have only set "errors" in levels, but i still get warnings in grafana/loki. Error with level "info" I get correctly not.

![image](https://github.com/cebe/yii2-loki-log-target/assets/60043850/25b2ed23-2908-478a-ae5c-0b3d52e5ff76)

UPDATE:

messages with level "info" are also displayed

![image](https://github.com/cebe/yii2-loki-log-target/assets/60043850/dca86e0e-7f8e-4daf-85da-3d427dd350a6)

UPDATE2:

It only affects the remapped exceptions, which are correctly mapped to warning/info, but are still sent to loki, since apparently the original level ("error") is used for it

                'levelMap' => [
                    // yii category
                    'yii\web\HttpException:404' => [
                        // yii level => loki level
                        '*' => 'info',
                    ],
                    'yii\web\HttpException:401' => [
                        // yii level => loki level
                        '*' => 'warning',
                    ],
                ],

**Comment by cebe** [comment]
> It only affects the remapped exceptions, which are correctly mapped to warning/info, but are still sent to loki, since apparently the original level ("error") is used for it

Message are filtered first, mapping is applied afterwards.
